name: chat_app_fe
description: "A new Flutter project."

# Prevent accidental publishing
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Networking
  dio: ^5.9.1
  retrofit: ^4.9.2
  web_socket_channel: ^3.0.3

  # Local storage
  shared_preferences: ^2.5.4
  path_provider: ^2.1.5

  # Routing
  auto_route: ^11.1.0

  # State management & utils
  flutter_bloc: ^9.1.1
  get_it: ^9.2.0
  dartz: ^0.10.1

  # Code generation annotations
  freezed_annotation: ^3.1.0
  json_annotation: ^4.10.0

  # UI & UX
  flex_color_scheme: ^8.4.0
  intl: ^0.20.2
  qr_flutter: ^4.1.0
  shimmer: ^3.0.0
  flutter_switch: ^0.3.2
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Code generation
  build_runner: ^2.10.5
  freezed: ^3.2.4
  json_serializable: ^6.11.3
  auto_route_generator: ^10.4.0
  retrofit_generator: ^10.2.1

  # Lints
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
